# Generated by Django 6.1.1 on 2026-09-13 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_category_food_category'),
        ('orders', '0002_remove_order_food_remove_order_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(to='orders.items_order'),
        ),
        migrations.RemoveField(
            model_name='items_order',
            name='food',
        ),
        migrations.AddField(
            model_name='items_order',
            name='food',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foods.food'),
            preserve_default=False,
        ),
    ]
