# Generated by Django 6.1.1 on 2026-09-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_items_order_order_order_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food',
            new_name='items',
        ),
    ]
